version: '3.8'
services:
  app:
    build: .
    volumes:
      - ../Statement_Data:/data
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/test_database

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mongo-data:
