version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: python_app
    restart: always
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    volumes:
      - statement_data:/data/statements

volumes:
  mongodb_data:
  prefect:
  statement_data:
