name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTHON_ENV: develop
  PYTHON_PATH: .

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}  # Add this line to properly checkout the repository
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run linter
      run: |
        flake8
    - name: Format code
      run: |
        black .
    - name: Open src
      working-directory: src/
      run: |
        ls -la
        find src
    - name: Test with pytest
      run: |
        export PYTHON_ENV=develop
        pytest
