name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTHON_ENV: develop
  PYTHON_PATH: .

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}  # Add this line to properly checkout the repository
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.13  # Pin the Poetry version if needed
    - name: Install dependencies using Poetry
      run: |
        poetry config virtualenvs.create false
        poetry install --no-dev
    - name: Run linter
      run: |
        flake8
    - name: Format code
      run: |
        black .
    - name: Test with pytest
      working-directory: .
      run: |
        export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
        export PYTHON_ENV=develop
        pytest tests
